language: python
python:
  - "2.7"
services:
  - mongodb
before_install: "sudo apt-get install build-essential python-dev libevent-dev"
install:
  - "python ./setup.py -q install"
  - "pip install -r requirements.txt --use-mirrors"
script: nosetests
